#!/usr/bin/env bash

if [ -d "arm" ]; then
	echo "Don't need to extract arm"
else
	tar -xvf arm.tar.gz
fi

#sudo echo '@reboot /home/pi/PIHomeSecurity/start-server.py' > /var/spool/cron/crontabs/pi
#sudo cp ./arm/bin/ffmpeg /usr/bin/
