#!/usr/bin/env bash

sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo apt-get install git

sudo apt-get install motion
#wget https://bootstrap.pypa.io/get-pip.py
#sudo python get-pip.py
#pip install requests
#pip install flask

sudo cp configs/motion.conf /etc/motion/
sudo cp configs/motion /etc/default/

sudo crontab -l > mycron
sudo echo "@reboot /home/pi/PIHomeSecurity/start-server.py" >> mycron
sudo echo "@reboot sudo modprobe bcm2835-v4l2" >> mycron
crontab mycron
rm mycron
